name: Execute workflow

on: 
  push:
  
jobs:
  execute:
    runs-on: ubuntu-latest
    
    steps:
      - name: first command
        run: echo "Hello World!"
      - name: print current directory
        run: pwd
      - name: mutliple commands
        run: |
          pwd
          ls -la
          date
          whoami