name: My First GitHub Workflow

on:
  push:

jobs:
  hello-world:

    runs-on: ubuntu-latest

    steps:

      - name: Print Welcome Message
        run: echo "Welcome to GitHub Actions"
        
      - name: Print Time
        run: timedatectl